name: Java Testing Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Compile Test files
      # recursively compile all files in the "tests" directory and sub-directories
      run: find tests -name '*.java' -print0 | xargs -0 javac -cp "bin:libs/*" -d bin

    - name: Run Test files
      # recursively run all files in the "tests" directory and sub-directories
      # this than strips the .class ending and converts all "/" from the directory URI into "."
      run: java --enable-preview -cp bin:libs/* org.junit.runner.JUnitCore $(find bin -name "*Test.class" -type f | sed 's@^bin/\(.*\)\.class$@\1@' | sed 's@/@.@g')

